# Generated by Django 5.2.6 on 2025-09-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('gu', 'Gujarati'), ('ta', 'Tamil'), ('bn', 'Bengali')], default='en', max_length=5)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
