# Generated by Django 5.1.4 on 2025-09-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0002_careerdataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerDataset',
        ),
    ]
