# Generated by Django 5.2.6 on 2025-09-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0004_learnerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='learnerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='de.user'),
        ),
    ]
